/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'paymentStatus' : IDL.Variant({
    'paymentConfirmed' : IDL.Null,
    'awaitingVerification' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'orderId' : IDL.Nat,
  'prescriptionNote' : IDL.Opt(IDL.Text),
  'address' : IDL.Record({
    'city' : IDL.Text,
    'line1' : IDL.Text,
    'pincode' : IDL.Text,
  }),
  'timestamp' : Time,
  'items' : IDL.Vec(
    IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
  ),
  'phoneNumber' : IDL.Text,
  'totalPrice' : IDL.Float64,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const Category = IDL.Variant({
  'vitaminsSupplements' : IDL.Null,
  'medicalEquipment' : IDL.Null,
  'personalCare' : IDL.Null,
  'medicines' : IDL.Null,
  'firstAid' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
  'stockAvailable' : IDL.Bool,
});
export const PlaceOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'prescriptionNote' : IDL.Opt(IDL.Text),
  'address' : IDL.Record({
    'city' : IDL.Text,
    'line1' : IDL.Text,
    'pincode' : IDL.Text,
  }),
  'items' : IDL.Vec(
    IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
  ),
  'phoneNumber' : IDL.Text,
});
export const PlaceOrderResponse = IDL.Record({
  'orderId' : IDL.Nat,
  'timestamp' : Time,
  'totalPrice' : IDL.Float64,
});

export const idlService = IDL.Service({
  'clearAllData' : IDL.Func([], [], []),
  'confirmPayment' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getConfirmedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByPhoneNumber' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getPendingPaymentOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [PlaceOrderResponse], []),
  'rejectPayment' : IDL.Func([IDL.Nat], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedProducts' : IDL.Func([], [], ['oneway']),
  'submitPaymentProof' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'paymentStatus' : IDL.Variant({
      'paymentConfirmed' : IDL.Null,
      'awaitingVerification' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'orderId' : IDL.Nat,
    'prescriptionNote' : IDL.Opt(IDL.Text),
    'address' : IDL.Record({
      'city' : IDL.Text,
      'line1' : IDL.Text,
      'pincode' : IDL.Text,
    }),
    'timestamp' : Time,
    'items' : IDL.Vec(
      IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
    ),
    'phoneNumber' : IDL.Text,
    'totalPrice' : IDL.Float64,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const Category = IDL.Variant({
    'vitaminsSupplements' : IDL.Null,
    'medicalEquipment' : IDL.Null,
    'personalCare' : IDL.Null,
    'medicines' : IDL.Null,
    'firstAid' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
    'stockAvailable' : IDL.Bool,
  });
  const PlaceOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'prescriptionNote' : IDL.Opt(IDL.Text),
    'address' : IDL.Record({
      'city' : IDL.Text,
      'line1' : IDL.Text,
      'pincode' : IDL.Text,
    }),
    'items' : IDL.Vec(
      IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat })
    ),
    'phoneNumber' : IDL.Text,
  });
  const PlaceOrderResponse = IDL.Record({
    'orderId' : IDL.Nat,
    'timestamp' : Time,
    'totalPrice' : IDL.Float64,
  });
  
  return IDL.Service({
    'clearAllData' : IDL.Func([], [], []),
    'confirmPayment' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getConfirmedOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getPendingPaymentOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [PlaceOrderResponse], []),
    'rejectPayment' : IDL.Func([IDL.Nat], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedProducts' : IDL.Func([], [], ['oneway']),
    'submitPaymentProof' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };