/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'vitaminsSupplements' : null } |
  { 'medicalEquipment' : null } |
  { 'personalCare' : null } |
  { 'medicines' : null } |
  { 'firstAid' : null };
export interface Order {
  'customerName' : string,
  'orderId' : bigint,
  'prescriptionNote' : [] | [string],
  'address' : { 'city' : string, 'line1' : string, 'pincode' : string },
  'timestamp' : Time,
  'items' : Array<{ 'productId' : bigint, 'quantity' : bigint }>,
  'phoneNumber' : string,
  'totalPrice' : number,
}
export interface PlaceOrderRequest {
  'customerName' : string,
  'prescriptionNote' : [] | [string],
  'address' : { 'city' : string, 'line1' : string, 'pincode' : string },
  'items' : Array<{ 'productId' : bigint, 'quantity' : bigint }>,
  'phoneNumber' : string,
}
export interface PlaceOrderResponse {
  'orderId' : bigint,
  'timestamp' : Time,
  'totalPrice' : number,
}
export interface Product {
  'id' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
  'stockAvailable' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'clearAllData' : ActorMethod<[], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByPhoneNumber' : ActorMethod<[string], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'initialize' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], PlaceOrderResponse>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedProducts' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];