/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlaceOrderRequest {
    customerName: string;
    prescriptionNote?: string;
    address: {
        city: string;
        line1: string;
        pincode: string;
    };
    items: Array<{
        productId: bigint;
        quantity: bigint;
    }>;
    phoneNumber: string;
}
export interface PlaceOrderResponse {
    orderId: bigint;
    timestamp: Time;
    totalPrice: number;
}
export type Time = bigint;
export interface Order {
    customerName: string;
    paymentStatus: Variant_paymentConfirmed_awaitingVerification_rejected;
    orderId: bigint;
    prescriptionNote?: string;
    address: {
        city: string;
        line1: string;
        pincode: string;
    };
    timestamp: Time;
    items: Array<{
        productId: bigint;
        quantity: bigint;
    }>;
    phoneNumber: string;
    totalPrice: number;
    transactionId?: string;
}
export interface Product {
    id: bigint;
    featured: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: number;
    stockAvailable: boolean;
}
export enum Category {
    vitaminsSupplements = "vitaminsSupplements",
    medicalEquipment = "medicalEquipment",
    personalCare = "personalCare",
    medicines = "medicines",
    firstAid = "firstAid"
}
export enum Variant_paymentConfirmed_awaitingVerification_rejected {
    paymentConfirmed = "paymentConfirmed",
    awaitingVerification = "awaitingVerification",
    rejected = "rejected"
}
export interface backendInterface {
    clearAllData(): Promise<void>;
    confirmPayment(orderId: bigint): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getAllProducts(): Promise<Array<Product>>;
    getConfirmedOrders(): Promise<Array<Order>>;
    getFeaturedProducts(): Promise<Array<Product>>;
    getOrder(orderId: bigint): Promise<Order | null>;
    getOrdersByPhoneNumber(phoneNumber: string): Promise<Array<Order>>;
    getPendingPaymentOrders(): Promise<Array<Order>>;
    getProductById(id: bigint): Promise<Product | null>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    initialize(): Promise<void>;
    placeOrder(request: PlaceOrderRequest): Promise<PlaceOrderResponse>;
    rejectPayment(orderId: bigint): Promise<void>;
    searchProducts(searchTerm: string): Promise<Array<Product>>;
    seedProducts(): Promise<void>;
    submitPaymentProof(orderId: bigint, transactionId: string): Promise<void>;
}
import type { Category as _Category, Order as _Order, PlaceOrderRequest as _PlaceOrderRequest, Product as _Product, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllData();
            return result;
        }
    }
    async confirmPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfirmedOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfirmedOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfirmedOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByPhoneNumber(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByPhoneNumber(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByPhoneNumber(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPaymentOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPaymentOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPaymentOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<PlaceOrderResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPayment(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
    async submitPaymentProof(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentProof(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentProof(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    paymentStatus: {
        paymentConfirmed: null;
    } | {
        awaitingVerification: null;
    } | {
        rejected: null;
    };
    orderId: bigint;
    prescriptionNote: [] | [string];
    address: {
        city: string;
        line1: string;
        pincode: string;
    };
    timestamp: _Time;
    items: Array<{
        productId: bigint;
        quantity: bigint;
    }>;
    phoneNumber: string;
    totalPrice: number;
    transactionId: [] | [string];
}): {
    customerName: string;
    paymentStatus: Variant_paymentConfirmed_awaitingVerification_rejected;
    orderId: bigint;
    prescriptionNote?: string;
    address: {
        city: string;
        line1: string;
        pincode: string;
    };
    timestamp: Time;
    items: Array<{
        productId: bigint;
        quantity: bigint;
    }>;
    phoneNumber: string;
    totalPrice: number;
    transactionId?: string;
} {
    return {
        customerName: value.customerName,
        paymentStatus: from_candid_variant_n4(_uploadFile, _downloadFile, value.paymentStatus),
        orderId: value.orderId,
        prescriptionNote: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.prescriptionNote)),
        address: value.address,
        timestamp: value.timestamp,
        items: value.items,
        phoneNumber: value.phoneNumber,
        totalPrice: value.totalPrice,
        transactionId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    featured: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    price: number;
    stockAvailable: boolean;
}): {
    id: bigint;
    featured: boolean;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: number;
    stockAvailable: boolean;
} {
    return {
        id: value.id,
        featured: value.featured,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        price: value.price,
        stockAvailable: value.stockAvailable
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vitaminsSupplements: null;
} | {
    medicalEquipment: null;
} | {
    personalCare: null;
} | {
    medicines: null;
} | {
    firstAid: null;
}): Category {
    return "vitaminsSupplements" in value ? Category.vitaminsSupplements : "medicalEquipment" in value ? Category.medicalEquipment : "personalCare" in value ? Category.personalCare : "medicines" in value ? Category.medicines : "firstAid" in value ? Category.firstAid : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentConfirmed: null;
} | {
    awaitingVerification: null;
} | {
    rejected: null;
}): Variant_paymentConfirmed_awaitingVerification_rejected {
    return "paymentConfirmed" in value ? Variant_paymentConfirmed_awaitingVerification_rejected.paymentConfirmed : "awaitingVerification" in value ? Variant_paymentConfirmed_awaitingVerification_rejected.awaitingVerification : "rejected" in value ? Variant_paymentConfirmed_awaitingVerification_rejected.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderRequest): _PlaceOrderRequest {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    prescriptionNote?: string;
    address: {
        city: string;
        line1: string;
        pincode: string;
    };
    items: Array<{
        productId: bigint;
        quantity: bigint;
    }>;
    phoneNumber: string;
}): {
    customerName: string;
    prescriptionNote: [] | [string];
    address: {
        city: string;
        line1: string;
        pincode: string;
    };
    items: Array<{
        productId: bigint;
        quantity: bigint;
    }>;
    phoneNumber: string;
} {
    return {
        customerName: value.customerName,
        prescriptionNote: value.prescriptionNote ? candid_some(value.prescriptionNote) : candid_none(),
        address: value.address,
        items: value.items,
        phoneNumber: value.phoneNumber
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    vitaminsSupplements: null;
} | {
    medicalEquipment: null;
} | {
    personalCare: null;
} | {
    medicines: null;
} | {
    firstAid: null;
} {
    return value == Category.vitaminsSupplements ? {
        vitaminsSupplements: null
    } : value == Category.medicalEquipment ? {
        medicalEquipment: null
    } : value == Category.personalCare ? {
        personalCare: null
    } : value == Category.medicines ? {
        medicines: null
    } : value == Category.firstAid ? {
        firstAid: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
